import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import sidebar from "./component/sidebar";
import pagemagin from "./component/pagemargin";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "TIJ Inventory",
  description: "TIJ Inventory Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      
      <body className={inter.className}>
      {sidebar()}
      <div className="flex flex-col sm:ml-60 sm:border-r sm:border-zinc-700 min-h-screen">
        
        {children}
      </div>
        
      </body>
    </html>
  );
}
